//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exxis.Addon.RegistroCompCCRR.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exxis.Addon.RegistroCompCCRR.CrossCutting.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] The column match for the &apos;MatrixBuilder&apos; has errors.
        /// </summary>
        public static string BadMatchMatrixBuilder {
            get {
                return ResourceManager.GetString("BadMatchMatrixBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] Can&apos;t load the class &apos;ApplicationSettings&apos; because {0}.
        /// </summary>
        public static string LoadApplicationSettings {
            get {
                return ResourceManager.GetString("LoadApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] The expression &apos;{0}&apos; doesn&apos;t have implemented in this version.
        /// </summary>
        public static string MissmatchExpression {
            get {
                return ResourceManager.GetString("MissmatchExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] The value &apos;{0}&apos; doesn&apos;t have implemented in this version.
        /// </summary>
        public static string MissmatchSAPDatabaseType {
            get {
                return ResourceManager.GetString("MissmatchSAPDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] The class &apos;{0}&apos; is not reference/base type for &apos;{1}&apos;.
        /// </summary>
        public static string MissmatchType {
            get {
                return ResourceManager.GetString("MissmatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] The instance of &apos;{0}&apos; doesn&apos;t have implemented in this version.
        /// </summary>
        public static string NoImplemented {
            get {
                return ResourceManager.GetString("NoImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] Error con el API externo ({0}) - {1}.
        /// </summary>
        public static string NotConnectWithAPI {
            get {
                return ResourceManager.GetString("NotConnectWithAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Internal Error] The class &apos;{0}&apos; don&apos;t have required attribute &apos;{1}&apos;.
        /// </summary>
        public static string RequiredAttributeDontFound {
            get {
                return ResourceManager.GetString("RequiredAttributeDontFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La linea &apos;{0}&apos; del documento no posee suficientes articulos a distribuir.
        /// </summary>
        public static string SaleOrderValidationError {
            get {
                return ResourceManager.GetString("SaleOrderValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La linea &apos;{0}&apos; del documento tiene un TVU superior a lo disponible.
        /// </summary>
        public static string SaleOrderValidationErrorTVU {
            get {
                return ResourceManager.GetString("SaleOrderValidationErrorTVU", resourceCulture);
            }
        }
    }
}
